### ISSUE TITLE
Error when changing the language of webtrees

### ISSUE THREAD

**Issue by hartenthaler** [hieberst/webtrees-extended-slide-show#1]
I have not checked why this is happening.

ErrorException: file(/mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/extended-slide-show/resources/lang/en-GB/messages.po): Failed to open stream: No such file or directory in /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/fisharebest/localization/src/Translation.php:56 Stack trace: #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}() #1 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/fisharebest/localization/src/Translation.php(56): file() #2 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/extended-slide-show/ExtendedSlideShowModule.php(74): Fisharebest\Localization\Translation->__construct() #3 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/I18N.php(303): Hieberst\Webtrees\Module\ExtendedSlideShowModule->customTranslations() #4 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/illuminate/collections/Traits/EnumeratesValues.php(768): Fisharebest\Webtrees\I18N::Fisharebest\Webtrees\{closure}() #5 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/I18N.php(302): Illuminate\Support\Collection->reduce() #6 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/UseLanguage.php(65): Fisharebest\Webtrees\I18N::init() #7 /

**Comment by hieberst** [comment]
The exception is thrown because I had just playfully added German as a translation and hadn't considered switching to another language.
