### ISSUE TITLE
make wt 2.2 compatible

### ISSUE THREAD

**Issue by arbor95** [hieberst/webtrees-extended-slide-show#2]
Fatal error in module: extended-slide-show
Error: Call to undefined method Fisharebest\Webtrees\Webtrees::make() in ....../webtrees/modules_v4/extended-slide-show/module.php:29 Stack trace: #0 

replace app( by ...

**Comment by hieberst** [comment]
wt 2.1.21 and above has added the lifespan, this module is not necessary any more
